#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:student
#spring.datasource.username=practice
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/practice
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource.username=practice
#spring.h2.console.enabled=true
#spring.jpa.show-sql=true
welcome:
  message: welcome to springboot

spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile:
      - reg
  datasource:
    username: practice
    url: jdbc:mysql://localhost:3306/practice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
---

spring:
  config:
    activate:
      on-profile:
      - prod
  datasource:
    username: root
    password: 8450
    url: jdbc:mysql://localhost:3306/practice-prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
  endpoint:
    beans:
      enabled: false